/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CoaLibraryRouteImport } from './routes/coa-library'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrderReceivedOrderIdRouteImport } from './routes/order-received.$orderId'
import { Route as OrderPayOrderIdRouteImport } from './routes/order-pay.$orderId'
import { Route as OrderConfirmationOrderIdRouteImport } from './routes/order-confirmation.$orderId'
import { Route as AccountOrdersRouteImport } from './routes/account.orders'
import { Route as ApiPublicWooStoreRouteImport } from './routes/api/public/woo-store'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CoaLibraryRoute = CoaLibraryRouteImport.update({
  id: '/coa-library',
  path: '/coa-library',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderReceivedOrderIdRoute = OrderReceivedOrderIdRouteImport.update({
  id: '/order-received/$orderId',
  path: '/order-received/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderPayOrderIdRoute = OrderPayOrderIdRouteImport.update({
  id: '/order-pay/$orderId',
  path: '/order-pay/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderConfirmationOrderIdRoute =
  OrderConfirmationOrderIdRouteImport.update({
    id: '/order-confirmation/$orderId',
    path: '/order-confirmation/$orderId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AccountOrdersRoute = AccountOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AccountRoute,
} as any)
const ApiPublicWooStoreRoute = ApiPublicWooStoreRouteImport.update({
  id: '/api/public/woo-store',
  path: '/api/public/woo-store',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/coa-library': typeof CoaLibraryRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/shop': typeof ShopRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/account/orders': typeof AccountOrdersRoute
  '/order-confirmation/$orderId': typeof OrderConfirmationOrderIdRoute
  '/order-pay/$orderId': typeof OrderPayOrderIdRoute
  '/order-received/$orderId': typeof OrderReceivedOrderIdRoute
  '/api/public/woo-store': typeof ApiPublicWooStoreRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/coa-library': typeof CoaLibraryRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/shop': typeof ShopRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/account/orders': typeof AccountOrdersRoute
  '/order-confirmation/$orderId': typeof OrderConfirmationOrderIdRoute
  '/order-pay/$orderId': typeof OrderPayOrderIdRoute
  '/order-received/$orderId': typeof OrderReceivedOrderIdRoute
  '/api/public/woo-store': typeof ApiPublicWooStoreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/coa-library': typeof CoaLibraryRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/shop': typeof ShopRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/account/orders': typeof AccountOrdersRoute
  '/order-confirmation/$orderId': typeof OrderConfirmationOrderIdRoute
  '/order-pay/$orderId': typeof OrderPayOrderIdRoute
  '/order-received/$orderId': typeof OrderReceivedOrderIdRoute
  '/api/public/woo-store': typeof ApiPublicWooStoreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/checkout'
    | '/coa-library'
    | '/contact'
    | '/disclaimer'
    | '/faq'
    | '/login'
    | '/privacy'
    | '/shop'
    | '/sign-in'
    | '/sign-up'
    | '/signup'
    | '/terms'
    | '/account/orders'
    | '/order-confirmation/$orderId'
    | '/order-pay/$orderId'
    | '/order-received/$orderId'
    | '/api/public/woo-store'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/checkout'
    | '/coa-library'
    | '/contact'
    | '/disclaimer'
    | '/faq'
    | '/login'
    | '/privacy'
    | '/shop'
    | '/sign-in'
    | '/sign-up'
    | '/signup'
    | '/terms'
    | '/account/orders'
    | '/order-confirmation/$orderId'
    | '/order-pay/$orderId'
    | '/order-received/$orderId'
    | '/api/public/woo-store'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/checkout'
    | '/coa-library'
    | '/contact'
    | '/disclaimer'
    | '/faq'
    | '/login'
    | '/privacy'
    | '/shop'
    | '/sign-in'
    | '/sign-up'
    | '/signup'
    | '/terms'
    | '/account/orders'
    | '/order-confirmation/$orderId'
    | '/order-pay/$orderId'
    | '/order-received/$orderId'
    | '/api/public/woo-store'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRouteWithChildren
  CheckoutRoute: typeof CheckoutRoute
  CoaLibraryRoute: typeof CoaLibraryRoute
  ContactRoute: typeof ContactRoute
  DisclaimerRoute: typeof DisclaimerRoute
  FaqRoute: typeof FaqRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ShopRoute: typeof ShopRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  OrderConfirmationOrderIdRoute: typeof OrderConfirmationOrderIdRoute
  OrderPayOrderIdRoute: typeof OrderPayOrderIdRoute
  OrderReceivedOrderIdRoute: typeof OrderReceivedOrderIdRoute
  ApiPublicWooStoreRoute: typeof ApiPublicWooStoreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coa-library': {
      id: '/coa-library'
      path: '/coa-library'
      fullPath: '/coa-library'
      preLoaderRoute: typeof CoaLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-received/$orderId': {
      id: '/order-received/$orderId'
      path: '/order-received/$orderId'
      fullPath: '/order-received/$orderId'
      preLoaderRoute: typeof OrderReceivedOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-pay/$orderId': {
      id: '/order-pay/$orderId'
      path: '/order-pay/$orderId'
      fullPath: '/order-pay/$orderId'
      preLoaderRoute: typeof OrderPayOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-confirmation/$orderId': {
      id: '/order-confirmation/$orderId'
      path: '/order-confirmation/$orderId'
      fullPath: '/order-confirmation/$orderId'
      preLoaderRoute: typeof OrderConfirmationOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/orders': {
      id: '/account/orders'
      path: '/orders'
      fullPath: '/account/orders'
      preLoaderRoute: typeof AccountOrdersRouteImport
      parentRoute: typeof AccountRoute
    }
    '/api/public/woo-store': {
      id: '/api/public/woo-store'
      path: '/api/public/woo-store'
      fullPath: '/api/public/woo-store'
      preLoaderRoute: typeof ApiPublicWooStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AccountRouteChildren {
  AccountOrdersRoute: typeof AccountOrdersRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountOrdersRoute: AccountOrdersRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
  CoaLibraryRoute: CoaLibraryRoute,
  ContactRoute: ContactRoute,
  DisclaimerRoute: DisclaimerRoute,
  FaqRoute: FaqRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ShopRoute: ShopRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  OrderConfirmationOrderIdRoute: OrderConfirmationOrderIdRoute,
  OrderPayOrderIdRoute: OrderPayOrderIdRoute,
  OrderReceivedOrderIdRoute: OrderReceivedOrderIdRoute,
  ApiPublicWooStoreRoute: ApiPublicWooStoreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
